spring.application.name=reddit

# --- DATABASE CONFIGURATION ---
#spring.datasource.url=jdbc:postgresql://ep-holy-glitter-a19f3p4l-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_oZe30GRAyPjB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://dpg-d1ui1svdiees73apano0-a.oregon-postgres.render.com:5432/redditdb_q8p1
spring.datasource.username=redditdb_q8p1_user
spring.datasource.password=gDr2o6pdryg6tmEBirJlKzXF4VTmlAlz

#spring.datasource.url=jdbc:postgresql://localhost:5432/reddit
#spring.datasource.username=postgres
#spring.datasource.password=root123

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


#logging.level.root=ERROR
spring.main.banner-mode=off

# Cloudinary config
cloudinary.cloud-name=dnvs6hb4f
cloudinary.api-key=947846433316797
cloudinary.api-secret=1jfcGqNnGQ3dmDfgAshwAD-BdmA

#spring:
#security:
#oauth2:
#client:
#registration:
#google:
#client-id: 232465453645-qhqnr8mq0u51jrj8l32ms8mnomik4sou.apps.googleusercontent.com
#client-secret: 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
#scope:
#- email
#- profile
#redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
spring.security.oauth2.client.registration.google.client-id=232465453645-qhqnr8mq0u51jrj8l32ms8mnomik4sou.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
