spring.application.name=reddit

# --- DATABASE CONFIGURATION ---
spring.datasource.url=jdbc:postgresql://ep-holy-glitter-a19f3p4l-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oZe30GRAyPjB
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


logging.level.root=ERROR
spring.main.banner-mode=off

# Cloudinary config
cloudinary.cloud-name=dnvs6hb4f
cloudinary.api-key=947846433316797
cloudinary.api-secret=1jfcGqNnGQ3dmDfgAshwAD-BdmA
